package handshake;

import java.security.MessageDigest;
import java.util.Arrays;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;

/**
 * HandshakeManager is responsible ONLY for:
 * - Deriving the shared session key
 * 
 * Important after bug fix:
 * - The preMaster secret must be generated by the CLIENT, NOT here in the handshake manager like before
 * - The same preMaster must be used on BOTH sides --> Solved by no longer having the handshake manager create it
 */
public class HandshakeManager {

    /**
     * Derives a symmetric session key using:
     * preMaster + clientRandom + serverRandom
     *
     * This MUST be identical on both client and server
     */
    public static SecretKey deriveSessionKey(byte[] preMaster,
                                             byte[] clientRandom,
                                             byte[] serverRandom) throws Exception {

        // Step 1: Hash all handshake inputs using SHA-256
        MessageDigest md = MessageDigest.getInstance("SHA-256");

        md.update(preMaster);
        md.update(clientRandom);
        md.update(serverRandom);

        byte[] fullHash = md.digest();

        // Step 2: Use first 16 bytes for AES-128 key
        byte[] keyBytes = Arrays.copyOf(fullHash, 16);

        return new SecretKeySpec(keyBytes, "AES");
    }
}